### PR TITLE
Feature ansible vault

### PR DESCRIPTION
**Pull request by RebelCodeBase**
I've added support for [ansible-vault](https://docs.ansible.com/ansible/2.5/user_guide/vault.html) by using the [gem ansible-vault](https://github.com/tpickett66/ansible-vault-rb). I've created one test case and fixed some spelling mistakes.

### CODE REVIEW

**Comment by volanja** [comment]
I think that it is a good idea.
However, in 1.9.3 & 2.0.0 version the test fails.
This is problem of `ansible-vault`.
Since the test fails, I want to take some measures.
Please let me know if you have any good ideas.

**Comment by RebelCodeBase** [comment]
According to the [travis-ci output](https://travis-ci.org/volanja/ansible_spec/jobs/403341377) the problem is the use of [required keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments) in [vault.rb](https://github.com/tpickett66/ansible-vault-rb/blob/master/lib/ansible/vault.rb) which have been [introduced with ruby 2.1](https://github.com/ruby/ruby/blob/v2_1_0/NEWS). "Unfortunately" this seems to be a legitimate usage of this feature in ansible-vault-rb so it makes no sense to propose a "downgrade". As the support of [ruby 2.2 has ended](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/) I propose to stop supporting ruby 1.9.3 and 2.0.0 for this gem. What do you think about it?

**Comment by volanja** [comment]
Thank you for researching.
certainly ruby 1.9.3 &2.0.0 is deprecated.
But serverspec is tested from ruby 1.8.3 to 2.5.0
(see : https://travis-ci.org/mizzy/serverspec)
So I want to support similar version.

By the way, I'm concern that `ansible-vault-rb` is not perhaps maintananced. 
because `ansible-vault-rb` last commit was 2 years ago...

**Comment by RebelCodeBase** [comment]
I've [asked](https://github.com/tpickett66/ansible-vault-rb/issues/10) Tyler Pickett if his gem is still maintained. If it is we could add some code to only require it if the ruby version is bigger or equal to 2.1.

**Comment by volanja** [comment]
You responded that the author of `ansible-vault-rb` is maintaining it.
Therefore, I would like to merge this PR. AndI will add some changes to fix the test failure.

**Pull request merged**
