### PR TITLE
Added feature set path to group_vars and host_vars

### PR DESCRIPTION
**Pull request by rbramwell**
Added feature to allow setting the directory path where the group_vars
and host_vars are located. This is an optional feature and as such it
does not break the existing fuctionality. This would allow the
adjustment of the search paths to support multi-staged environment
layouts such as the Alternative Direcory Layout at
http://docs.ansible.com/ansible/playbooks_best_practices.html

### CODE REVIEW

**Comment by volanja** [comment]
Thank you for your PR.
Could you add some test case?

**Comment by rbramwell** [comment]
@volanja Tests cases added

**Comment by rbramwell** [comment]
**Example usage of 'vars_dirs_path' option**

Scenario, you are using a multi-staged environment layout (as below). With the 
current behaviour of ansible_spec, you will not be able to search group_vars
and host_vars unless they are in the playbook base directory (e.g. where 
site.yml is located below). Using the inventory setting and vars_dirs_path 
.ansible_spec variable or VARS_DIRS_PATH environment variable, the behavior can
be adapted to allow group_vars and host_vars directories to be searched/read
given a directory path to a directory containing group_vars and host_vars directories.
e.g. vars_dirs_path: 'inventories/staging'

Example multi-staged envirnment directory layout:

 ├── site.yml
 ├── inventories
 │   ├── development
 |   |   ├── group_vars
 |   |   │   ├── all.yml
 |   |   │   ├── dbserver.yml
 |   |   │   └── webserver.yml
 |   |   └── host_vars
 |   |       ├── 192.168.1.1.yml
 |   |       └── 192.168.1.2.yml
 │   ├── production
 |   |   ├── group_vars
 |   |   │   ├── all.yml
 |   |   │   ├── dbserver.yml
 |   |   │   └── webserver.yml
 |   |   └── host_vars
 |   |       ├── 192.168.10.1.yml
 |   |       └── 192.168.10.2.yml
 │   └── staging
 |       ├── group_vars
 |       │   ├── all.yml
 |       │   ├── dbserver.yml
 |       │   └── webserver.yml
 |       └── host_vars
 |           ├── 192.168.20.1.yml
 |           └── 192.168.20.2.yml
 └── roles
     ├── apaches
     │   └── vars
     │       └── main.yml
     └── mariadb
         └── vars
             └── main.yml

An example .ansiblespec file to achieve the above goal:
---
-
  playbook: 'site.yml'
  inventory: 'inventories/staging/hosts'
  vars_dirs_path: 'inventories/staging'
---

An example execution of a ansible_spec rake task:

  PLAYBOOK='site.yml' \
  INVENTORY='inventories/staging/hosts' \
  VARS_DIRS_PATH='inventories/staging' \
  rake serverspec:Ansible-Sample-TDD

**Comment by volanja** [comment]
Thank you for add some test case.
I checked & merged it.

**Comment by rbramwell** [comment]
That's great! Glad to have contributed.

**Pull request merged**
